trigger:
  branches:
    include:
    - refs/heads/feature
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: vs2017-win2016
  steps:
  - checkout: self
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      TargetFolder: $(build.artifactstagingdirectory)
  - task: PublishPipelineArtifact@1
    displayName: Publish Pipeline Artifact
...
